# Generated by Django 5.0.1 on 2024-02-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dishes',
        ),
    ]
