# Generated by Django 5.0.1 on 2024-02-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_table_alter_dish_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='desctiption',
            new_name='description',
        ),
    ]
